version: '3'

services:
  ufabc-enrollment-api:
    build:
      ./pdf-parser/
    container_name: ufabc_enrollment_api
    volumes:
        - ./docs:/app/docs/
    restart: always
    ports:
      - "8100:8080"
